server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        index index.html;
    }

    location /Souvera.ipa {
        types { application/octet-stream ipa; }
        add_header Content-Disposition "attachment; filename=Souvera.ipa";
    }

    location /manifest.plist {
        default_type text/xml;
        add_header Content-Type text/xml;
        add_header X-Content-Type-Options nosniff;
    }

    location ~ \.ipa$ {
        default_type application/octet-stream;
        add_header Content-Type application/octet-stream;
    }

    location = /ota {
        default_type text/xml;
        add_header Content-Type text/xml;
    }
}
