server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        index index.html;
    }

    location /Souvera.ipa {
        types { application/octet-stream ipa; }
        add_header Content-Disposition "attachment; filename=Souvera.ipa";
    }

    location /manifest.plist {
        types { application/x-plist plist; }
    }
}
